const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIN_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIN_SUCCESS',
    FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
};

export default ShopActionTypes;